# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in json_structure.gemspec
gemspec

group :development, :test do
  gem 'rake', '~> 13.0'
  gem 'rspec', '~> 3.0'
  gem 'rubocop', '~> 1.50'
end
