{
  "type": "record",
  "name": "Settings",
  "fields": [
    {
      "name": "id",
      "type": "string"
    },
    {
      "name": "retries",
      "type": [
        "int",
        "null"
      ],
      "default": 3
    },
    {
      "name": "label",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "enabled",
      "type": [
        "boolean",
        "null"
      ],
      "default": true
    },
    {
      "name": "effectiveDate",
      "type": [
        {
          "type": "int",
          "logicalType": "date"
        },
        "null"
      ],
      "default": 1
    },
    {
      "name": "referencedDate",
      "type": [
        {
          "type": "int",
          "logicalType": "date"
        },
        "null"
      ],
      "default": 2
    },
    {
      "name": "dateOrBoolean",
      "type": [
        {
          "type": "int",
          "logicalType": "date"
        },
        "boolean",
        "null"
      ],
      "default": 3
    },
    {
      "name": "kind",
      "type": [
        "null",
        "string"
      ],
      "default": null
    }
  ]
}
