"""
Standardized error codes for JSON Structure validation.
These codes are consistent across all SDK implementations.
"""

from dataclasses import dataclass
from enum import Enum
from typing import Optional


class ValidationSeverity(Enum):
    """Severity of a validation message."""
    ERROR = "error"
    WARNING = "warning"


@dataclass(frozen=True)
class JsonLocation:
    """Represents a location in a JSON document with line and column information."""
    line: int
    column: int
    
    @classmethod
    def unknown(cls) -> "JsonLocation":
        """Returns an unknown location (line 0, column 0)."""
        return cls(0, 0)
    
    @property
    def is_known(self) -> bool:
        """Returns True if the location is known (non-zero)."""
        return self.line > 0 and self.column > 0
    
    def __str__(self) -> str:
        """Returns a string representation like '(line:column)'."""
        return f"({self.line}:{self.column})" if self.is_known else ""


@dataclass
class ValidationError:
    """Represents a validation error with code, message, and location information."""
    code: str
    message: str
    path: str = ""
    severity: ValidationSeverity = ValidationSeverity.ERROR
    location: JsonLocation = None
    schema_path: Optional[str] = None
    
    def __post_init__(self):
        if self.location is None:
            self.location = JsonLocation.unknown()
    
    def __str__(self) -> str:
        """Returns a formatted string representation of the error."""
        parts = []
        
        if self.path:
            parts.append(self.path)
        
        if self.location.is_known:
            parts.append(str(self.location))
        
        parts.append(f"[{self.code}]")
        parts.append(self.message)
        
        if self.schema_path:
            parts.append(f"(schema: {self.schema_path})")
        
        return " ".join(parts)
    
    def __contains__(self, item: str) -> bool:
        """Support 'in' operator for backward compatibility with string checks."""
        return item in str(self) or item in self.message
    
    def lower(self) -> str:
        """Support .lower() for backward compatibility with string operations."""
        return str(self).lower()


# Schema Validation Errors (SCHEMA_*)

SCHEMA_ERROR = "SCHEMA_ERROR"
"""Generic schema error."""

SCHEMA_NULL = "SCHEMA_NULL"
"""Schema cannot be null."""

SCHEMA_INVALID_TYPE = "SCHEMA_INVALID_TYPE"
"""Schema must be a boolean or object."""

SCHEMA_MAX_DEPTH_EXCEEDED = "SCHEMA_MAX_DEPTH_EXCEEDED"
"""Maximum validation depth exceeded."""

SCHEMA_KEYWORD_INVALID_TYPE = "SCHEMA_KEYWORD_INVALID_TYPE"
"""Keyword has invalid type."""

SCHEMA_KEYWORD_EMPTY = "SCHEMA_KEYWORD_EMPTY"
"""Keyword cannot be empty."""

SCHEMA_TYPE_INVALID = "SCHEMA_TYPE_INVALID"
"""Invalid type name."""

SCHEMA_TYPE_ARRAY_EMPTY = "SCHEMA_TYPE_ARRAY_EMPTY"
"""Type array cannot be empty."""

SCHEMA_TYPE_OBJECT_MISSING_REF = "SCHEMA_TYPE_OBJECT_MISSING_REF"
"""Type object must contain $ref."""

SCHEMA_REF_NOT_FOUND = "SCHEMA_REF_NOT_FOUND"
"""$ref target does not exist."""

SCHEMA_REF_INVALID = "SCHEMA_REF_INVALID"
"""Invalid $ref value."""

SCHEMA_REF_CIRCULAR = "SCHEMA_REF_CIRCULAR"
"""Circular reference detected."""

SCHEMA_EXTENDS_CIRCULAR = "SCHEMA_EXTENDS_CIRCULAR"
"""Circular $extends reference detected."""

SCHEMA_EXTENDS_NOT_FOUND = "SCHEMA_EXTENDS_NOT_FOUND"
"""$extends reference not found."""

SCHEMA_REF_NOT_IN_TYPE = "SCHEMA_REF_NOT_IN_TYPE"
"""$ref is only permitted inside the 'type' attribute."""

SCHEMA_MISSING_TYPE = "SCHEMA_MISSING_TYPE"
"""Schema must have a 'type' keyword."""

SCHEMA_ROOT_MISSING_TYPE = "SCHEMA_ROOT_MISSING_TYPE"
"""Root schema must have 'type', '$root', or other schema-defining keyword."""

SCHEMA_ROOT_MISSING_ID = "SCHEMA_ROOT_MISSING_ID"
"""Root schema must have an '$id' keyword."""

SCHEMA_ROOT_MISSING_NAME = "SCHEMA_ROOT_MISSING_NAME"
"""Root schema with 'type' must have a 'name' property."""

SCHEMA_NAME_INVALID = "SCHEMA_NAME_INVALID"
"""Name is not a valid identifier."""

SCHEMA_CONSTRAINT_INVALID_FOR_TYPE = "SCHEMA_CONSTRAINT_INVALID_FOR_TYPE"
"""Constraint is not valid for this type."""

SCHEMA_MIN_GREATER_THAN_MAX = "SCHEMA_MIN_GREATER_THAN_MAX"
"""Minimum cannot be greater than maximum."""

SCHEMA_PROPERTIES_NOT_OBJECT = "SCHEMA_PROPERTIES_NOT_OBJECT"
"""Properties must be an object."""

SCHEMA_REQUIRED_NOT_ARRAY = "SCHEMA_REQUIRED_NOT_ARRAY"
"""Required must be an array."""

SCHEMA_REQUIRED_ITEM_NOT_STRING = "SCHEMA_REQUIRED_ITEM_NOT_STRING"
"""Required array items must be strings."""

SCHEMA_REQUIRED_PROPERTY_NOT_DEFINED = "SCHEMA_REQUIRED_PROPERTY_NOT_DEFINED"
"""Required property is not defined in properties."""

SCHEMA_ADDITIONAL_PROPERTIES_INVALID = "SCHEMA_ADDITIONAL_PROPERTIES_INVALID"
"""additionalProperties must be a boolean or schema."""

SCHEMA_ARRAY_MISSING_ITEMS = "SCHEMA_ARRAY_MISSING_ITEMS"
"""Array type requires 'items' schema."""

SCHEMA_TUPLE_MISSING_DEFINITION = "SCHEMA_TUPLE_MISSING_DEFINITION"
"""Tuple type requires 'properties' and 'tuple' keywords."""

SCHEMA_TUPLE_ORDER_NOT_ARRAY = "SCHEMA_TUPLE_ORDER_NOT_ARRAY"
"""'tuple' keyword must be an array of property names."""

SCHEMA_MAP_MISSING_VALUES = "SCHEMA_MAP_MISSING_VALUES"
"""Map type requires 'values' schema."""

SCHEMA_CHOICE_MISSING_CHOICES = "SCHEMA_CHOICE_MISSING_CHOICES"
"""Choice type requires 'choices' keyword."""

SCHEMA_CHOICES_NOT_OBJECT = "SCHEMA_CHOICES_NOT_OBJECT"
"""Choices must be an object."""

SCHEMA_PATTERN_INVALID = "SCHEMA_PATTERN_INVALID"
"""Pattern is not a valid regular expression."""

SCHEMA_PATTERN_NOT_STRING = "SCHEMA_PATTERN_NOT_STRING"
"""Pattern must be a string."""

SCHEMA_ENUM_NOT_ARRAY = "SCHEMA_ENUM_NOT_ARRAY"
"""Enum must be an array."""

SCHEMA_ENUM_EMPTY = "SCHEMA_ENUM_EMPTY"
"""Enum array cannot be empty."""

SCHEMA_ENUM_DUPLICATE_VALUE = "SCHEMA_ENUM_DUPLICATE_VALUE"
"""Enum array contains duplicate values."""

SCHEMA_ENUM_DUPLICATES = "SCHEMA_ENUM_DUPLICATES"
"""Enum array contains duplicate values."""

SCHEMA_COMPOSITION_EMPTY = "SCHEMA_COMPOSITION_EMPTY"
"""Composition keyword array cannot be empty."""

SCHEMA_COMPOSITION_NOT_ARRAY = "SCHEMA_COMPOSITION_NOT_ARRAY"
"""Composition keyword must be an array."""

SCHEMA_ALTNAMES_NOT_OBJECT = "SCHEMA_ALTNAMES_NOT_OBJECT"
"""altnames must be an object."""

SCHEMA_ALTNAMES_VALUE_NOT_STRING = "SCHEMA_ALTNAMES_VALUE_NOT_STRING"
"""altnames values must be strings."""

SCHEMA_INTEGER_CONSTRAINT_INVALID = "SCHEMA_INTEGER_CONSTRAINT_INVALID"
"""Keyword must be a non-negative integer."""

SCHEMA_NUMBER_CONSTRAINT_INVALID = "SCHEMA_NUMBER_CONSTRAINT_INVALID"
"""Keyword must be a number."""

SCHEMA_POSITIVE_NUMBER_CONSTRAINT_INVALID = "SCHEMA_POSITIVE_NUMBER_CONSTRAINT_INVALID"
"""Keyword must be a positive number."""

SCHEMA_UNIQUE_ITEMS_NOT_BOOLEAN = "SCHEMA_UNIQUE_ITEMS_NOT_BOOLEAN"
"""uniqueItems must be a boolean."""

SCHEMA_ITEMS_INVALID_FOR_TUPLE = "SCHEMA_ITEMS_INVALID_FOR_TUPLE"
"""items must be a boolean or schema for tuple type."""

SCHEMA_ROOT_CONFLICT = "SCHEMA_ROOT_CONFLICT"
"""Schema cannot have both 'type' and '$root' at root level."""

SCHEMA_USES_UNKNOWN_EXTENSION = "SCHEMA_USES_UNKNOWN_EXTENSION"
"""Unknown extension in $uses array."""

SCHEMA_EXTENSION_KEYWORD_NOT_ENABLED = "SCHEMA_EXTENSION_KEYWORD_NOT_ENABLED"
"""Validation extension keyword is used but validation extensions are not enabled."""

SCHEMA_CONSTRAINT_TYPE_MISMATCH = "SCHEMA_CONSTRAINT_TYPE_MISMATCH"
"""Constraint is not valid for this type."""

SCHEMA_CONSTRAINT_VALUE_INVALID = "SCHEMA_CONSTRAINT_VALUE_INVALID"
"""Constraint value is invalid."""

SCHEMA_CONSTRAINT_RANGE_INVALID = "SCHEMA_CONSTRAINT_RANGE_INVALID"
"""Constraint range is invalid (min > max)."""

SCHEMA_CHOICE_MISSING_CHOICES = "SCHEMA_CHOICE_MISSING_CHOICES"
"""Choice type requires 'choices' property."""

SCHEMA_TUPLE_MISSING_ORDER = "SCHEMA_TUPLE_MISSING_ORDER"
"""Tuple type requires 'tuple' property to define element order."""

SCHEMA_TUPLE_PROPERTY_NOT_DEFINED = "SCHEMA_TUPLE_PROPERTY_NOT_DEFINED"
"""Tuple element not found in properties."""


# Instance Validation Errors (INSTANCE_*)

INSTANCE_ROOT_UNRESOLVED = "INSTANCE_ROOT_UNRESOLVED"
"""Unable to resolve $root reference."""

INSTANCE_MAX_DEPTH_EXCEEDED = "INSTANCE_MAX_DEPTH_EXCEEDED"
"""Maximum validation depth exceeded."""

INSTANCE_SCHEMA_FALSE = "INSTANCE_SCHEMA_FALSE"
"""Schema 'false' rejects all values."""

INSTANCE_REF_UNRESOLVED = "INSTANCE_REF_UNRESOLVED"
"""Unable to resolve reference."""

INSTANCE_CONST_MISMATCH = "INSTANCE_CONST_MISMATCH"
"""Value must equal const value."""

INSTANCE_ENUM_MISMATCH = "INSTANCE_ENUM_MISMATCH"
"""Value must be one of the enum values."""

INSTANCE_ANY_OF_NONE_MATCHED = "INSTANCE_ANY_OF_NONE_MATCHED"
"""Value must match at least one schema in anyOf."""

INSTANCE_ONE_OF_INVALID_COUNT = "INSTANCE_ONE_OF_INVALID_COUNT"
"""Value must match exactly one schema in oneOf."""

INSTANCE_NOT_MATCHED = "INSTANCE_NOT_MATCHED"
"""Value must not match the schema in 'not'."""

INSTANCE_TYPE_UNKNOWN = "INSTANCE_TYPE_UNKNOWN"
"""Unknown type."""

INSTANCE_TYPE_MISMATCH = "INSTANCE_TYPE_MISMATCH"
"""Type mismatch."""

INSTANCE_NULL_EXPECTED = "INSTANCE_NULL_EXPECTED"
"""Value must be null."""

INSTANCE_BOOLEAN_EXPECTED = "INSTANCE_BOOLEAN_EXPECTED"
"""Value must be a boolean."""

INSTANCE_STRING_EXPECTED = "INSTANCE_STRING_EXPECTED"
"""Value must be a string."""

INSTANCE_STRING_MIN_LENGTH = "INSTANCE_STRING_MIN_LENGTH"
"""String length is less than minimum."""

INSTANCE_STRING_MAX_LENGTH = "INSTANCE_STRING_MAX_LENGTH"
"""String length exceeds maximum."""

INSTANCE_STRING_PATTERN_MISMATCH = "INSTANCE_STRING_PATTERN_MISMATCH"
"""String does not match pattern."""

INSTANCE_PATTERN_INVALID = "INSTANCE_PATTERN_INVALID"
"""Invalid regex pattern."""

INSTANCE_FORMAT_EMAIL_INVALID = "INSTANCE_FORMAT_EMAIL_INVALID"
"""String is not a valid email address."""

INSTANCE_FORMAT_URI_INVALID = "INSTANCE_FORMAT_URI_INVALID"
"""String is not a valid URI."""

INSTANCE_FORMAT_URI_REFERENCE_INVALID = "INSTANCE_FORMAT_URI_REFERENCE_INVALID"
"""String is not a valid URI reference."""

INSTANCE_FORMAT_DATE_INVALID = "INSTANCE_FORMAT_DATE_INVALID"
"""String is not a valid date."""

INSTANCE_FORMAT_TIME_INVALID = "INSTANCE_FORMAT_TIME_INVALID"
"""String is not a valid time."""

INSTANCE_FORMAT_DATETIME_INVALID = "INSTANCE_FORMAT_DATETIME_INVALID"
"""String is not a valid date-time."""

INSTANCE_FORMAT_UUID_INVALID = "INSTANCE_FORMAT_UUID_INVALID"
"""String is not a valid UUID."""

INSTANCE_FORMAT_IPV4_INVALID = "INSTANCE_FORMAT_IPV4_INVALID"
"""String is not a valid IPv4 address."""

INSTANCE_FORMAT_IPV6_INVALID = "INSTANCE_FORMAT_IPV6_INVALID"
"""String is not a valid IPv6 address."""

INSTANCE_FORMAT_HOSTNAME_INVALID = "INSTANCE_FORMAT_HOSTNAME_INVALID"
"""String is not a valid hostname."""

INSTANCE_NUMBER_EXPECTED = "INSTANCE_NUMBER_EXPECTED"
"""Value must be a number."""

INSTANCE_INTEGER_EXPECTED = "INSTANCE_INTEGER_EXPECTED"
"""Value must be an integer."""

INSTANCE_INT_RANGE_INVALID = "INSTANCE_INT_RANGE_INVALID"
"""Integer value is out of range."""

INSTANCE_NUMBER_MINIMUM = "INSTANCE_NUMBER_MINIMUM"
"""Value is less than minimum."""

INSTANCE_NUMBER_MAXIMUM = "INSTANCE_NUMBER_MAXIMUM"
"""Value exceeds maximum."""

INSTANCE_NUMBER_EXCLUSIVE_MINIMUM = "INSTANCE_NUMBER_EXCLUSIVE_MINIMUM"
"""Value must be greater than exclusive minimum."""

INSTANCE_NUMBER_EXCLUSIVE_MAXIMUM = "INSTANCE_NUMBER_EXCLUSIVE_MAXIMUM"
"""Value must be less than exclusive maximum."""

INSTANCE_NUMBER_MULTIPLE_OF = "INSTANCE_NUMBER_MULTIPLE_OF"
"""Value is not a multiple of the specified value."""

INSTANCE_OBJECT_EXPECTED = "INSTANCE_OBJECT_EXPECTED"
"""Value must be an object."""

INSTANCE_REQUIRED_PROPERTY_MISSING = "INSTANCE_REQUIRED_PROPERTY_MISSING"
"""Missing required property."""

INSTANCE_ADDITIONAL_PROPERTY_NOT_ALLOWED = "INSTANCE_ADDITIONAL_PROPERTY_NOT_ALLOWED"
"""Additional property not allowed."""

INSTANCE_MIN_PROPERTIES = "INSTANCE_MIN_PROPERTIES"
"""Object has fewer properties than minimum."""

INSTANCE_MAX_PROPERTIES = "INSTANCE_MAX_PROPERTIES"
"""Object has more properties than maximum."""

INSTANCE_DEPENDENT_REQUIRED = "INSTANCE_DEPENDENT_REQUIRED"
"""Dependent required property is missing."""

INSTANCE_ARRAY_EXPECTED = "INSTANCE_ARRAY_EXPECTED"
"""Value must be an array."""

INSTANCE_MIN_ITEMS = "INSTANCE_MIN_ITEMS"
"""Array has fewer items than minimum."""

INSTANCE_MAX_ITEMS = "INSTANCE_MAX_ITEMS"
"""Array has more items than maximum."""

INSTANCE_MIN_CONTAINS = "INSTANCE_MIN_CONTAINS"
"""Array has fewer matching items than minContains."""

INSTANCE_MAX_CONTAINS = "INSTANCE_MAX_CONTAINS"
"""Array has more matching items than maxContains."""

INSTANCE_SET_EXPECTED = "INSTANCE_SET_EXPECTED"
"""Value must be an array (set)."""

INSTANCE_SET_DUPLICATE = "INSTANCE_SET_DUPLICATE"
"""Set contains duplicate value."""

INSTANCE_MAP_EXPECTED = "INSTANCE_MAP_EXPECTED"
"""Value must be an object (map)."""

INSTANCE_MAP_MIN_ENTRIES = "INSTANCE_MAP_MIN_ENTRIES"
"""Map has fewer entries than minimum."""

INSTANCE_MAP_MAX_ENTRIES = "INSTANCE_MAP_MAX_ENTRIES"
"""Map has more entries than maximum."""

INSTANCE_MAP_KEY_INVALID = "INSTANCE_MAP_KEY_INVALID"
"""Map key does not match keyNames or patternKeys constraint."""

INSTANCE_TUPLE_EXPECTED = "INSTANCE_TUPLE_EXPECTED"
"""Value must be an array (tuple)."""

INSTANCE_TUPLE_LENGTH_MISMATCH = "INSTANCE_TUPLE_LENGTH_MISMATCH"
"""Tuple length does not match schema."""

INSTANCE_TUPLE_ADDITIONAL_ITEMS = "INSTANCE_TUPLE_ADDITIONAL_ITEMS"
"""Tuple has additional items not defined in schema."""

INSTANCE_CHOICE_EXPECTED = "INSTANCE_CHOICE_EXPECTED"
"""Value must be an object (choice)."""

INSTANCE_CHOICE_MISSING_CHOICES = "INSTANCE_CHOICE_MISSING_CHOICES"
"""Choice schema is missing choices."""

INSTANCE_CHOICE_SELECTOR_MISSING = "INSTANCE_CHOICE_SELECTOR_MISSING"
"""Choice selector property is missing."""

INSTANCE_CHOICE_SELECTOR_NOT_STRING = "INSTANCE_CHOICE_SELECTOR_NOT_STRING"
"""Selector value must be a string."""

INSTANCE_CHOICE_UNKNOWN = "INSTANCE_CHOICE_UNKNOWN"
"""Unknown choice."""

INSTANCE_CHOICE_NO_MATCH = "INSTANCE_CHOICE_NO_MATCH"
"""Value does not match any choice option."""

INSTANCE_CHOICE_MULTIPLE_MATCHES = "INSTANCE_CHOICE_MULTIPLE_MATCHES"
"""Value matches multiple choice options."""

INSTANCE_DATE_EXPECTED = "INSTANCE_DATE_EXPECTED"
"""Date must be a string."""

INSTANCE_DATE_FORMAT_INVALID = "INSTANCE_DATE_FORMAT_INVALID"
"""Invalid date format."""

INSTANCE_TIME_EXPECTED = "INSTANCE_TIME_EXPECTED"
"""Time must be a string."""

INSTANCE_TIME_FORMAT_INVALID = "INSTANCE_TIME_FORMAT_INVALID"
"""Invalid time format."""

INSTANCE_DATETIME_EXPECTED = "INSTANCE_DATETIME_EXPECTED"
"""DateTime must be a string."""

INSTANCE_DATETIME_FORMAT_INVALID = "INSTANCE_DATETIME_FORMAT_INVALID"
"""Invalid datetime format."""

INSTANCE_DURATION_EXPECTED = "INSTANCE_DURATION_EXPECTED"
"""Duration must be a string."""

INSTANCE_DURATION_FORMAT_INVALID = "INSTANCE_DURATION_FORMAT_INVALID"
"""Invalid duration format."""

INSTANCE_UUID_EXPECTED = "INSTANCE_UUID_EXPECTED"
"""UUID must be a string."""

INSTANCE_UUID_FORMAT_INVALID = "INSTANCE_UUID_FORMAT_INVALID"
"""Invalid UUID format."""

INSTANCE_URI_EXPECTED = "INSTANCE_URI_EXPECTED"
"""URI must be a string."""

INSTANCE_URI_FORMAT_INVALID = "INSTANCE_URI_FORMAT_INVALID"
"""Invalid URI format."""

INSTANCE_URI_MISSING_SCHEME = "INSTANCE_URI_MISSING_SCHEME"
"""URI must have a scheme."""

INSTANCE_BINARY_EXPECTED = "INSTANCE_BINARY_EXPECTED"
"""Binary must be a base64 string."""

INSTANCE_BINARY_ENCODING_INVALID = "INSTANCE_BINARY_ENCODING_INVALID"
"""Invalid base64 encoding."""

INSTANCE_JSONPOINTER_EXPECTED = "INSTANCE_JSONPOINTER_EXPECTED"
"""JSON Pointer must be a string."""

INSTANCE_JSONPOINTER_FORMAT_INVALID = "INSTANCE_JSONPOINTER_FORMAT_INVALID"
"""Invalid JSON Pointer format."""

INSTANCE_DECIMAL_EXPECTED = "INSTANCE_DECIMAL_EXPECTED"
"""Value must be a valid decimal."""

INSTANCE_STRING_NOT_EXPECTED = "INSTANCE_STRING_NOT_EXPECTED"
"""String value not expected for this type."""

INSTANCE_CUSTOM_TYPE_NOT_SUPPORTED = "INSTANCE_CUSTOM_TYPE_NOT_SUPPORTED"
"""Custom type reference not yet supported."""


# Dictionary of all error codes for easy lookup
ERROR_CODES = {
    # Schema errors
    "SCHEMA_NULL": SCHEMA_NULL,
    "SCHEMA_INVALID_TYPE": SCHEMA_INVALID_TYPE,
    "SCHEMA_MAX_DEPTH_EXCEEDED": SCHEMA_MAX_DEPTH_EXCEEDED,
    "SCHEMA_KEYWORD_INVALID_TYPE": SCHEMA_KEYWORD_INVALID_TYPE,
    "SCHEMA_KEYWORD_EMPTY": SCHEMA_KEYWORD_EMPTY,
    "SCHEMA_TYPE_INVALID": SCHEMA_TYPE_INVALID,
    "SCHEMA_TYPE_ARRAY_EMPTY": SCHEMA_TYPE_ARRAY_EMPTY,
    "SCHEMA_TYPE_OBJECT_MISSING_REF": SCHEMA_TYPE_OBJECT_MISSING_REF,
    "SCHEMA_REF_NOT_FOUND": SCHEMA_REF_NOT_FOUND,
    "SCHEMA_REF_CIRCULAR": SCHEMA_REF_CIRCULAR,
    "SCHEMA_EXTENDS_CIRCULAR": SCHEMA_EXTENDS_CIRCULAR,
    "SCHEMA_EXTENDS_NOT_FOUND": SCHEMA_EXTENDS_NOT_FOUND,
    "SCHEMA_REF_NOT_IN_TYPE": SCHEMA_REF_NOT_IN_TYPE,
    "SCHEMA_MISSING_TYPE": SCHEMA_MISSING_TYPE,
    "SCHEMA_ROOT_MISSING_TYPE": SCHEMA_ROOT_MISSING_TYPE,
    "SCHEMA_ROOT_MISSING_ID": SCHEMA_ROOT_MISSING_ID,
    "SCHEMA_ROOT_MISSING_NAME": SCHEMA_ROOT_MISSING_NAME,
    "SCHEMA_NAME_INVALID": SCHEMA_NAME_INVALID,
    "SCHEMA_CONSTRAINT_INVALID_FOR_TYPE": SCHEMA_CONSTRAINT_INVALID_FOR_TYPE,
    "SCHEMA_MIN_GREATER_THAN_MAX": SCHEMA_MIN_GREATER_THAN_MAX,
    "SCHEMA_PROPERTIES_NOT_OBJECT": SCHEMA_PROPERTIES_NOT_OBJECT,
    "SCHEMA_REQUIRED_NOT_ARRAY": SCHEMA_REQUIRED_NOT_ARRAY,
    "SCHEMA_REQUIRED_ITEM_NOT_STRING": SCHEMA_REQUIRED_ITEM_NOT_STRING,
    "SCHEMA_REQUIRED_PROPERTY_NOT_DEFINED": SCHEMA_REQUIRED_PROPERTY_NOT_DEFINED,
    "SCHEMA_ADDITIONAL_PROPERTIES_INVALID": SCHEMA_ADDITIONAL_PROPERTIES_INVALID,
    "SCHEMA_ARRAY_MISSING_ITEMS": SCHEMA_ARRAY_MISSING_ITEMS,
    "SCHEMA_TUPLE_MISSING_DEFINITION": SCHEMA_TUPLE_MISSING_DEFINITION,
    "SCHEMA_TUPLE_ORDER_NOT_ARRAY": SCHEMA_TUPLE_ORDER_NOT_ARRAY,
    "SCHEMA_MAP_MISSING_VALUES": SCHEMA_MAP_MISSING_VALUES,
    "SCHEMA_CHOICE_MISSING_CHOICES": SCHEMA_CHOICE_MISSING_CHOICES,
    "SCHEMA_CHOICES_NOT_OBJECT": SCHEMA_CHOICES_NOT_OBJECT,
    "SCHEMA_PATTERN_INVALID": SCHEMA_PATTERN_INVALID,
    "SCHEMA_PATTERN_NOT_STRING": SCHEMA_PATTERN_NOT_STRING,
    "SCHEMA_ENUM_NOT_ARRAY": SCHEMA_ENUM_NOT_ARRAY,
    "SCHEMA_ENUM_EMPTY": SCHEMA_ENUM_EMPTY,
    "SCHEMA_ENUM_DUPLICATES": SCHEMA_ENUM_DUPLICATES,
    "SCHEMA_COMPOSITION_EMPTY": SCHEMA_COMPOSITION_EMPTY,
    "SCHEMA_COMPOSITION_NOT_ARRAY": SCHEMA_COMPOSITION_NOT_ARRAY,
    "SCHEMA_ALTNAMES_NOT_OBJECT": SCHEMA_ALTNAMES_NOT_OBJECT,
    "SCHEMA_ALTNAMES_VALUE_NOT_STRING": SCHEMA_ALTNAMES_VALUE_NOT_STRING,
    "SCHEMA_INTEGER_CONSTRAINT_INVALID": SCHEMA_INTEGER_CONSTRAINT_INVALID,
    "SCHEMA_NUMBER_CONSTRAINT_INVALID": SCHEMA_NUMBER_CONSTRAINT_INVALID,
    "SCHEMA_POSITIVE_NUMBER_CONSTRAINT_INVALID": SCHEMA_POSITIVE_NUMBER_CONSTRAINT_INVALID,
    "SCHEMA_UNIQUE_ITEMS_NOT_BOOLEAN": SCHEMA_UNIQUE_ITEMS_NOT_BOOLEAN,
    "SCHEMA_ITEMS_INVALID_FOR_TUPLE": SCHEMA_ITEMS_INVALID_FOR_TUPLE,
    
    # Instance errors
    "INSTANCE_ROOT_UNRESOLVED": INSTANCE_ROOT_UNRESOLVED,
    "INSTANCE_MAX_DEPTH_EXCEEDED": INSTANCE_MAX_DEPTH_EXCEEDED,
    "INSTANCE_SCHEMA_FALSE": INSTANCE_SCHEMA_FALSE,
    "INSTANCE_REF_UNRESOLVED": INSTANCE_REF_UNRESOLVED,
    "INSTANCE_CONST_MISMATCH": INSTANCE_CONST_MISMATCH,
    "INSTANCE_ENUM_MISMATCH": INSTANCE_ENUM_MISMATCH,
    "INSTANCE_ANY_OF_NONE_MATCHED": INSTANCE_ANY_OF_NONE_MATCHED,
    "INSTANCE_ONE_OF_INVALID_COUNT": INSTANCE_ONE_OF_INVALID_COUNT,
    "INSTANCE_NOT_MATCHED": INSTANCE_NOT_MATCHED,
    "INSTANCE_TYPE_UNKNOWN": INSTANCE_TYPE_UNKNOWN,
    "INSTANCE_TYPE_MISMATCH": INSTANCE_TYPE_MISMATCH,
    "INSTANCE_NULL_EXPECTED": INSTANCE_NULL_EXPECTED,
    "INSTANCE_BOOLEAN_EXPECTED": INSTANCE_BOOLEAN_EXPECTED,
    "INSTANCE_STRING_EXPECTED": INSTANCE_STRING_EXPECTED,
    "INSTANCE_STRING_MIN_LENGTH": INSTANCE_STRING_MIN_LENGTH,
    "INSTANCE_STRING_MAX_LENGTH": INSTANCE_STRING_MAX_LENGTH,
    "INSTANCE_STRING_PATTERN_MISMATCH": INSTANCE_STRING_PATTERN_MISMATCH,
    "INSTANCE_PATTERN_INVALID": INSTANCE_PATTERN_INVALID,
    "INSTANCE_FORMAT_EMAIL_INVALID": INSTANCE_FORMAT_EMAIL_INVALID,
    "INSTANCE_FORMAT_URI_INVALID": INSTANCE_FORMAT_URI_INVALID,
    "INSTANCE_FORMAT_URI_REFERENCE_INVALID": INSTANCE_FORMAT_URI_REFERENCE_INVALID,
    "INSTANCE_FORMAT_DATE_INVALID": INSTANCE_FORMAT_DATE_INVALID,
    "INSTANCE_FORMAT_TIME_INVALID": INSTANCE_FORMAT_TIME_INVALID,
    "INSTANCE_FORMAT_DATETIME_INVALID": INSTANCE_FORMAT_DATETIME_INVALID,
    "INSTANCE_FORMAT_UUID_INVALID": INSTANCE_FORMAT_UUID_INVALID,
    "INSTANCE_FORMAT_IPV4_INVALID": INSTANCE_FORMAT_IPV4_INVALID,
    "INSTANCE_FORMAT_IPV6_INVALID": INSTANCE_FORMAT_IPV6_INVALID,
    "INSTANCE_FORMAT_HOSTNAME_INVALID": INSTANCE_FORMAT_HOSTNAME_INVALID,
    "INSTANCE_NUMBER_EXPECTED": INSTANCE_NUMBER_EXPECTED,
    "INSTANCE_INTEGER_EXPECTED": INSTANCE_INTEGER_EXPECTED,
    "INSTANCE_INT_RANGE_INVALID": INSTANCE_INT_RANGE_INVALID,
    "INSTANCE_NUMBER_MINIMUM": INSTANCE_NUMBER_MINIMUM,
    "INSTANCE_NUMBER_MAXIMUM": INSTANCE_NUMBER_MAXIMUM,
    "INSTANCE_NUMBER_EXCLUSIVE_MINIMUM": INSTANCE_NUMBER_EXCLUSIVE_MINIMUM,
    "INSTANCE_NUMBER_EXCLUSIVE_MAXIMUM": INSTANCE_NUMBER_EXCLUSIVE_MAXIMUM,
    "INSTANCE_NUMBER_MULTIPLE_OF": INSTANCE_NUMBER_MULTIPLE_OF,
    "INSTANCE_OBJECT_EXPECTED": INSTANCE_OBJECT_EXPECTED,
    "INSTANCE_REQUIRED_PROPERTY_MISSING": INSTANCE_REQUIRED_PROPERTY_MISSING,
    "INSTANCE_ADDITIONAL_PROPERTY_NOT_ALLOWED": INSTANCE_ADDITIONAL_PROPERTY_NOT_ALLOWED,
    "INSTANCE_MIN_PROPERTIES": INSTANCE_MIN_PROPERTIES,
    "INSTANCE_MAX_PROPERTIES": INSTANCE_MAX_PROPERTIES,
    "INSTANCE_DEPENDENT_REQUIRED": INSTANCE_DEPENDENT_REQUIRED,
    "INSTANCE_ARRAY_EXPECTED": INSTANCE_ARRAY_EXPECTED,
    "INSTANCE_MIN_ITEMS": INSTANCE_MIN_ITEMS,
    "INSTANCE_MAX_ITEMS": INSTANCE_MAX_ITEMS,
    "INSTANCE_MIN_CONTAINS": INSTANCE_MIN_CONTAINS,
    "INSTANCE_MAX_CONTAINS": INSTANCE_MAX_CONTAINS,
    "INSTANCE_SET_EXPECTED": INSTANCE_SET_EXPECTED,
    "INSTANCE_SET_DUPLICATE": INSTANCE_SET_DUPLICATE,
    "INSTANCE_MAP_EXPECTED": INSTANCE_MAP_EXPECTED,
    "INSTANCE_MAP_MIN_ENTRIES": INSTANCE_MAP_MIN_ENTRIES,
    "INSTANCE_MAP_MAX_ENTRIES": INSTANCE_MAP_MAX_ENTRIES,
    "INSTANCE_MAP_KEY_INVALID": INSTANCE_MAP_KEY_INVALID,
    "INSTANCE_TUPLE_EXPECTED": INSTANCE_TUPLE_EXPECTED,
    "INSTANCE_TUPLE_LENGTH_MISMATCH": INSTANCE_TUPLE_LENGTH_MISMATCH,
    "INSTANCE_TUPLE_ADDITIONAL_ITEMS": INSTANCE_TUPLE_ADDITIONAL_ITEMS,
    "INSTANCE_CHOICE_EXPECTED": INSTANCE_CHOICE_EXPECTED,
    "INSTANCE_CHOICE_MISSING_CHOICES": INSTANCE_CHOICE_MISSING_CHOICES,
    "INSTANCE_CHOICE_SELECTOR_MISSING": INSTANCE_CHOICE_SELECTOR_MISSING,
    "INSTANCE_CHOICE_SELECTOR_NOT_STRING": INSTANCE_CHOICE_SELECTOR_NOT_STRING,
    "INSTANCE_CHOICE_UNKNOWN": INSTANCE_CHOICE_UNKNOWN,
    "INSTANCE_CHOICE_NO_MATCH": INSTANCE_CHOICE_NO_MATCH,
    "INSTANCE_CHOICE_MULTIPLE_MATCHES": INSTANCE_CHOICE_MULTIPLE_MATCHES,
    "INSTANCE_DATE_EXPECTED": INSTANCE_DATE_EXPECTED,
    "INSTANCE_DATE_FORMAT_INVALID": INSTANCE_DATE_FORMAT_INVALID,
    "INSTANCE_TIME_EXPECTED": INSTANCE_TIME_EXPECTED,
    "INSTANCE_TIME_FORMAT_INVALID": INSTANCE_TIME_FORMAT_INVALID,
    "INSTANCE_DATETIME_EXPECTED": INSTANCE_DATETIME_EXPECTED,
    "INSTANCE_DATETIME_FORMAT_INVALID": INSTANCE_DATETIME_FORMAT_INVALID,
    "INSTANCE_DURATION_EXPECTED": INSTANCE_DURATION_EXPECTED,
    "INSTANCE_DURATION_FORMAT_INVALID": INSTANCE_DURATION_FORMAT_INVALID,
    "INSTANCE_UUID_EXPECTED": INSTANCE_UUID_EXPECTED,
    "INSTANCE_UUID_FORMAT_INVALID": INSTANCE_UUID_FORMAT_INVALID,
    "INSTANCE_URI_EXPECTED": INSTANCE_URI_EXPECTED,
    "INSTANCE_URI_FORMAT_INVALID": INSTANCE_URI_FORMAT_INVALID,
    "INSTANCE_URI_MISSING_SCHEME": INSTANCE_URI_MISSING_SCHEME,
    "INSTANCE_BINARY_EXPECTED": INSTANCE_BINARY_EXPECTED,
    "INSTANCE_BINARY_ENCODING_INVALID": INSTANCE_BINARY_ENCODING_INVALID,
    "INSTANCE_JSONPOINTER_EXPECTED": INSTANCE_JSONPOINTER_EXPECTED,
    "INSTANCE_JSONPOINTER_FORMAT_INVALID": INSTANCE_JSONPOINTER_FORMAT_INVALID,
    "INSTANCE_DECIMAL_EXPECTED": INSTANCE_DECIMAL_EXPECTED,
    "INSTANCE_STRING_NOT_EXPECTED": INSTANCE_STRING_NOT_EXPECTED,
    "INSTANCE_CUSTOM_TYPE_NOT_SUPPORTED": INSTANCE_CUSTOM_TYPE_NOT_SUPPORTED,
}
