/**
 * @file error_codes.h
 * @brief Error codes for JSON Structure validation
 * 
 * These error codes match the standardized codes in assets/error-messages.json.
 * 
 * Copyright (c) 2024 JSON Structure Contributors
 * SPDX-License-Identifier: MIT
 */

#ifndef JSON_STRUCTURE_ERROR_CODES_H
#define JSON_STRUCTURE_ERROR_CODES_H

#include "export.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Schema validation error codes
 */
typedef enum {
    /* General schema errors */
    JS_SCHEMA_OK = 0,
    JS_SCHEMA_NULL,
    JS_SCHEMA_INVALID_TYPE,
    JS_SCHEMA_MAX_DEPTH_EXCEEDED,
    JS_SCHEMA_ROOT_MISSING_ID,
    JS_SCHEMA_ROOT_MISSING_NAME,
    JS_SCHEMA_ROOT_MISSING_SCHEMA,
    JS_SCHEMA_ROOT_MISSING_TYPE,
    
    /* Type errors */
    JS_SCHEMA_TYPE_INVALID,
    JS_SCHEMA_TYPE_NOT_STRING,
    JS_SCHEMA_TYPE_ARRAY_EMPTY,
    JS_SCHEMA_TYPE_OBJECT_MISSING_REF,
    
    /* Reference errors */
    JS_SCHEMA_REF_NOT_FOUND,
    JS_SCHEMA_REF_NOT_STRING,
    JS_SCHEMA_REF_CIRCULAR,
    JS_SCHEMA_REF_INVALID,
    
    /* Definition errors */
    JS_SCHEMA_DEFINITIONS_MUST_BE_OBJECT,
    JS_SCHEMA_DEFINITION_MISSING_TYPE,
    JS_SCHEMA_DEFINITION_INVALID,
    
    /* Object property errors */
    JS_SCHEMA_PROPERTIES_MUST_BE_OBJECT,
    JS_SCHEMA_PROPERTY_INVALID,
    JS_SCHEMA_REQUIRED_MUST_BE_ARRAY,
    JS_SCHEMA_REQUIRED_ITEM_MUST_BE_STRING,
    JS_SCHEMA_REQUIRED_PROPERTY_NOT_DEFINED,
    JS_SCHEMA_ADDITIONAL_PROPERTIES_INVALID,
    
    /* Array/Set errors */
    JS_SCHEMA_ARRAY_MISSING_ITEMS,
    JS_SCHEMA_ITEMS_INVALID,
    
    /* Map errors */
    JS_SCHEMA_MAP_MISSING_VALUES,
    JS_SCHEMA_VALUES_INVALID,
    
    /* Tuple errors */
    JS_SCHEMA_TUPLE_MISSING_DEFINITION,
    JS_SCHEMA_TUPLE_MISSING_PROPERTIES,
    JS_SCHEMA_TUPLE_INVALID_FORMAT,
    JS_SCHEMA_TUPLE_PROPERTY_NOT_DEFINED,
    
    /* Choice errors */
    JS_SCHEMA_CHOICE_MISSING_CHOICES,
    JS_SCHEMA_CHOICES_NOT_OBJECT,
    JS_SCHEMA_CHOICE_INVALID,
    JS_SCHEMA_SELECTOR_NOT_STRING,
    
    /* Enum/Const errors */
    JS_SCHEMA_ENUM_NOT_ARRAY,
    JS_SCHEMA_ENUM_EMPTY,
    JS_SCHEMA_ENUM_DUPLICATES,
    JS_SCHEMA_CONST_INVALID,
    
    /* Extension errors */
    JS_SCHEMA_USES_NOT_ARRAY,
    JS_SCHEMA_USES_INVALID_EXTENSION,
    JS_SCHEMA_OFFERS_NOT_ARRAY,
    JS_SCHEMA_OFFERS_INVALID_EXTENSION,
    JS_SCHEMA_EXTENSION_KEYWORD_WITHOUT_USES,
    
    /* Constraint errors */
    JS_SCHEMA_MIN_MAX_INVALID,
    JS_SCHEMA_MINLENGTH_INVALID,
    JS_SCHEMA_MAXLENGTH_INVALID,
    JS_SCHEMA_PATTERN_INVALID,
    JS_SCHEMA_FORMAT_INVALID,
    JS_SCHEMA_CONSTRAINT_TYPE_MISMATCH,
    JS_SCHEMA_MINIMUM_EXCEEDS_MAXIMUM,
    JS_SCHEMA_MINLENGTH_EXCEEDS_MAXLENGTH,
    JS_SCHEMA_MINLENGTH_NEGATIVE,
    JS_SCHEMA_MAXLENGTH_NEGATIVE,
    JS_SCHEMA_MINITEMS_EXCEEDS_MAXITEMS,
    JS_SCHEMA_MINITEMS_NEGATIVE,
    JS_SCHEMA_MULTIPLEOF_INVALID,
    JS_SCHEMA_KEYWORD_INVALID_TYPE,
    
    /* Import errors */
    JS_SCHEMA_IMPORT_NOT_ALLOWED,
    JS_SCHEMA_IMPORT_FAILED,
    JS_SCHEMA_IMPORT_CIRCULAR,
    
    /* Composition errors */
    JS_SCHEMA_ALLOF_NOT_ARRAY,
    JS_SCHEMA_ANYOF_NOT_ARRAY,
    JS_SCHEMA_ONEOF_NOT_ARRAY,
    JS_SCHEMA_NOT_INVALID,
    JS_SCHEMA_IF_INVALID,
    JS_SCHEMA_THEN_WITHOUT_IF,
    JS_SCHEMA_ELSE_WITHOUT_IF,
    
    JS_SCHEMA_ERROR_COUNT
} js_schema_error_t;

/**
 * @brief Instance validation error codes
 */
typedef enum {
    /* Success */
    JS_INSTANCE_OK = 0,
    
    /* Type mismatch errors */
    JS_INSTANCE_TYPE_MISMATCH,
    JS_INSTANCE_TYPE_UNKNOWN,
    
    /* String errors */
    JS_INSTANCE_STRING_EXPECTED,
    JS_INSTANCE_STRING_TOO_SHORT,
    JS_INSTANCE_STRING_TOO_LONG,
    JS_INSTANCE_STRING_PATTERN_MISMATCH,
    JS_INSTANCE_STRING_FORMAT_INVALID,
    
    /* Number errors */
    JS_INSTANCE_NUMBER_EXPECTED,
    JS_INSTANCE_NUMBER_TOO_SMALL,
    JS_INSTANCE_NUMBER_TOO_LARGE,
    JS_INSTANCE_NUMBER_NOT_MULTIPLE,
    JS_INSTANCE_INTEGER_EXPECTED,
    JS_INSTANCE_INTEGER_OUT_OF_RANGE,
    
    /* Boolean/Null errors */
    JS_INSTANCE_BOOLEAN_EXPECTED,
    JS_INSTANCE_NULL_EXPECTED,
    
    /* Object errors */
    JS_INSTANCE_OBJECT_EXPECTED,
    JS_INSTANCE_REQUIRED_MISSING,
    JS_INSTANCE_ADDITIONAL_PROPERTY,
    JS_INSTANCE_PROPERTY_INVALID,
    JS_INSTANCE_TOO_FEW_PROPERTIES,
    JS_INSTANCE_TOO_MANY_PROPERTIES,
    JS_INSTANCE_DEPENDENT_REQUIRED_MISSING,
    
    /* Array errors */
    JS_INSTANCE_ARRAY_EXPECTED,
    JS_INSTANCE_ARRAY_TOO_SHORT,
    JS_INSTANCE_ARRAY_TOO_LONG,
    JS_INSTANCE_ARRAY_NOT_UNIQUE,
    JS_INSTANCE_ARRAY_CONTAINS_MISSING,
    JS_INSTANCE_ARRAY_CONTAINS_TOO_FEW,
    JS_INSTANCE_ARRAY_CONTAINS_TOO_MANY,
    JS_INSTANCE_ARRAY_ITEM_INVALID,
    
    /* Tuple errors */
    JS_INSTANCE_TUPLE_EXPECTED,
    JS_INSTANCE_TUPLE_LENGTH_MISMATCH,
    JS_INSTANCE_TUPLE_ELEMENT_INVALID,
    
    /* Map errors */
    JS_INSTANCE_MAP_EXPECTED,
    JS_INSTANCE_MAP_VALUE_INVALID,
    JS_INSTANCE_MAP_TOO_FEW_ENTRIES,
    JS_INSTANCE_MAP_TOO_MANY_ENTRIES,
    JS_INSTANCE_MAP_KEY_PATTERN_MISMATCH,
    
    /* Set errors */
    JS_INSTANCE_SET_EXPECTED,
    JS_INSTANCE_SET_NOT_UNIQUE,
    JS_INSTANCE_SET_ITEM_INVALID,
    
    /* Choice errors */
    JS_INSTANCE_CHOICE_NO_MATCH,
    JS_INSTANCE_CHOICE_MULTIPLE_MATCHES,
    JS_INSTANCE_CHOICE_UNKNOWN,
    JS_INSTANCE_CHOICE_SELECTOR_MISSING,
    JS_INSTANCE_CHOICE_SELECTOR_INVALID,
    
    /* Enum/Const errors */
    JS_INSTANCE_ENUM_MISMATCH,
    JS_INSTANCE_CONST_MISMATCH,
    
    /* Date/Time errors */
    JS_INSTANCE_DATE_EXPECTED,
    JS_INSTANCE_DATE_INVALID,
    JS_INSTANCE_TIME_EXPECTED,
    JS_INSTANCE_TIME_INVALID,
    JS_INSTANCE_DATETIME_EXPECTED,
    JS_INSTANCE_DATETIME_INVALID,
    JS_INSTANCE_DURATION_EXPECTED,
    JS_INSTANCE_DURATION_INVALID,
    
    /* UUID errors */
    JS_INSTANCE_UUID_EXPECTED,
    JS_INSTANCE_UUID_INVALID,
    
    /* URI errors */
    JS_INSTANCE_URI_EXPECTED,
    JS_INSTANCE_URI_INVALID,
    
    /* Binary errors */
    JS_INSTANCE_BINARY_EXPECTED,
    JS_INSTANCE_BINARY_INVALID,
    
    /* JSON Pointer errors */
    JS_INSTANCE_JSONPOINTER_EXPECTED,
    JS_INSTANCE_JSONPOINTER_INVALID,
    
    /* Composition errors */
    JS_INSTANCE_ALLOF_FAILED,
    JS_INSTANCE_ANYOF_FAILED,
    JS_INSTANCE_ONEOF_FAILED,
    JS_INSTANCE_ONEOF_MULTIPLE,
    JS_INSTANCE_NOT_FAILED,
    JS_INSTANCE_IF_THEN_FAILED,
    JS_INSTANCE_IF_ELSE_FAILED,
    
    /* Reference errors */
    JS_INSTANCE_REF_NOT_FOUND,
    
    /* Union errors */
    JS_INSTANCE_UNION_NO_MATCH,
    
    JS_INSTANCE_ERROR_COUNT
} js_instance_error_t;

/**
 * @brief Get the string representation of a schema error code
 * @param code The error code
 * @return Constant string (do not free)
 */
JS_API const char* js_schema_error_str(js_schema_error_t code);

/**
 * @brief Get the string representation of an instance error code
 * @param code The error code
 * @return Constant string (do not free)
 */
JS_API const char* js_instance_error_str(js_instance_error_t code);

#ifdef __cplusplus
}
#endif

#endif /* JSON_STRUCTURE_ERROR_CODES_H */
