{
  "type": "record",
  "name": "Lossless",
  "fields": [
    {
      "name": "dec",
      "type": "string"
    },
    {
      "name": "date",
      "type": "string"
    },
    {
      "name": "time",
      "type": "string"
    },
    {
      "name": "dt",
      "type": "string"
    },
    {
      "name": "dur",
      "type": "string"
    },
    {
      "name": "uuid",
      "type": "string"
    },
    {
      "name": "uri",
      "type": "string"
    },
    {
      "name": "ptr",
      "type": "string"
    },
    {
      "name": "i128",
      "type": "string"
    },
    {
      "name": "u64",
      "type": "string"
    },
    {
      "name": "u128",
      "type": "string"
    }
  ]
}
