{
  "type": "record",
  "name": "Money",
  "fields": [
    {
      "name": "carried",
      "type": {
        "type": "bytes",
        "logicalType": "decimal",
        "precision": 9,
        "scale": 2
      },
      "annotations": {
        "minimum": 0
      }
    },
    {
      "name": "noPrecision",
      "type": "string",
      "annotations": {
        "scale": 2,
        "maximum": 100
      }
    },
    {
      "name": "scaleOverPrecision",
      "type": "string",
      "annotations": {
        "precision": 2,
        "scale": 5
      }
    }
  ]
}
